version: '3'
services:
  twitter_app:
    build: .
    container_name: "twitter_api"
    depends_on:
      - mongodb2
    links:
      - mongodb2
  mongodb2:
    container_name: "mongodb2"
    image: "mongo:3.7-jessie"
    ports:
      - "27017:27017"
  mongo_q:
    build: ./webapp
    container_name: "webapp2"
volumes:
     - ./logs:logs
    depends_on:
     - mongodb2
    links:
     - mongodb2
    ports:
      - "0.0.0.0:5000:5000"
