version: '2'
services:
  twitter_api:
    container_name: "twitter_app"
    image: "danbaror/twittc:twitter_api"
    depends_on:
      - mongodb2
    links:
      - mongodb2
  mongodb2:
    container_name: "mongodb2"
    image: "mongo:3.7-jessie"
    ports:
      - "27017:27017"
  mongo_q2:
    container_name: "webapp"
    image: "danbaror/twittc:mongo_q"
    depends_on:
     - mongodb2
    links:
     - mongodb2
    ports:
     - "0.0.0.0:5000:5000"
